create database PES1UG20CS484_RAILWAY_RESERVATION;
use PES1UG20CS484_RAILWAY_RESERVATION;
show tables;
create table TRAIN_484(Train_no int NOT NULL, Train_type varchar(255), Train_name varchar(255), Source varchar(255), Destination varchar(255), Availibility boolean, Primary key(Train_no));
create table COMPARTMENT_484(Compartment_number int NOT NULL, Compartment_type varchar(255), Compartment_capacity int NOT NULL, Compartment_availibility boolean,Train_no int NOT NULL, constraint my_compartment Primary key(Compartment_number), Foreign key(Train_no) references TRAIN_484(Train_no));
create table ROUTE_INFO484(From_station_no int NOT NULL,From_station_name varchar(255), To_station_no int NOT NULL, To_station_name varchar(255), Distance int NOT NULL, Train_no int NOT NULL, constraint my_routeinfo Primary key(From_station_no, To_station_no, Train_no), Foreign key(Train_no) references TRAIN_484(Train_no));
create table USER_484(User_id int NOT NULL, User_type varchar(50), Fname varchar(50), Lname varchar(50), Age int, Date_of_birth date, Pincode int, Street_no int, Primary key(User_id));
create table USER_TRAIN_484(Train_no int NOT NULL, User_id int NOT NULL, Date_time_stamp timestamp, constraint my_user_train Primary key(Train_no, User_id, Date_time_stamp), Foreign key(Train_no) references TRAIN_484(Train_no), Foreign key(User_id) references USER_484(User_id));
create table USER_PHONE_484(User_id int NOT NULL, Phone_no int NOT NULL, constraint my_user_phone Primary key(User_id, Phone_no), Foreign key(User_id) references USER_484(User_id));
create table TICKET_484(Pnr int NOT NULL, Train_no int NOT NULL, Travel_date date, Departure varchar(50), Arrival varchar(50), Departure_time timestamp, Arrival_time timestamp, User_id int NOT NULL, Train_type varchar(255), Compartment_type varchar(255), Compartment_number int NOT NULL, Primary key(Pnr), Foreign key(User_id) references USER_484(User_id));
create table PAYMENT_INFO_484(Transaction_id int NOT NULL, Bank varchar(255), Card_number int NOT NULL, Price float, Pnr int NOT NULL, Primary key(Transaction_id), Foreign key(Pnr) references TICKET_484(Pnr));
create table TICKET_PASSENGER_484(Seat_no int NOT NULL, Name varchar(255), Age int, Pnr int NOT NULL, Primary key(Seat_no), Foreign key(Pnr) references TICKET_484(Pnr));
create table FARE_TABLE_484(Train_type varchar(255), Compartment_type varchar(255), Far_per_km float, constraint my_fare_table Primary key(Train_type, Compartment_type));
alter table TRAIN_484 modify column Train_type varchar(255) NOT NULL;
alter table TRAIN_484 modify column Train_name varchar(255) NOT NULL;
alter table TRAIN_484 alter Availibility set default '1';
alter table TRAIN_484 add unique(Train_name);
alter table USER_484 add check (Age>5);
alter table ROUTE_INFO484 rename ROUTE_INFO_484;
truncate USER_PHONE_484;
drop table USER_PHONE_484;